# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q-Jz0xBfG0GBqosbLlpThnPK_UWiO7bw
"""

import streamlit as st
import random

st.title('Test Streamlit')
st.write('Hello World!')

if st.button('Generate Random Number'):
  random_number = random.ranint(1,100)
  st.write(f'Random Number : {random_number}')